import { prisma } from '../lib/prisma';
import { logger } from '../lib/logger';

interface DeployInput {
  leadId: string;
  userId: string;
  projectName: string;
  files: Record<string, string>; // path -> content
  framework?: string;
}

/**
 * Creates a GitHub repo, pushes generated files, then triggers a Vercel deployment.
 */
export async function deployToVercel(input: DeployInput): Promise<{ deployUrl: string; repoUrl: string }> {
  const settings = await prisma.settings.findUnique({ where: { userId: input.userId } });

  if (!settings?.vercelConnected || !settings.vercelToken) {
    throw new Error('Vercel is not connected. Go to Settings to connect.');
  }
  if (!settings?.githubConnected || !settings.githubToken) {
    throw new Error('GitHub is not connected. Go to Settings to connect.');
  }

  // Track deployment
  const deployment = await prisma.deployment.create({
    data: {
      leadId: input.leadId,
      projectName: input.projectName,
      status: 'DEPLOYING',
    },
  });

  try {
    // 1. Create GitHub repo
    const repoName = sanitizeRepoName(input.projectName);
    const repo = await createGithubRepo(settings.githubToken, repoName);

    // 2. Push files to repo
    await pushFilesToRepo(settings.githubToken, settings.githubUsername!, repoName, input.files);

    // 3. Create Vercel project linked to the repo
    const vercelProject = await createVercelProject(
      settings.vercelToken,
      repoName,
      settings.githubUsername!,
      repoName,
      input.framework,
      settings.vercelTeamId || undefined,
    );

    // 4. Trigger deployment
    const deployResult = await triggerVercelDeployment(
      settings.vercelToken,
      vercelProject.id,
      settings.vercelTeamId || undefined,
    );

    // Update deployment record
    await prisma.deployment.update({
      where: { id: deployment.id },
      data: {
        status: 'DEPLOYED',
        projectUrl: `https://vercel.com/${settings.githubUsername}/${repoName}`,
        deployUrl: deployResult.url ? `https://${deployResult.url}` : null,
        repoUrl: repo.html_url,
      },
    });

    return {
      deployUrl: deployResult.url ? `https://${deployResult.url}` : '',
      repoUrl: repo.html_url,
    };
  } catch (err) {
    logger.error({ err, deploymentId: deployment.id }, 'Deployment failed');
    await prisma.deployment.update({
      where: { id: deployment.id },
      data: {
        status: 'FAILED',
        errorMsg: err instanceof Error ? err.message : 'Unknown error',
      },
    });
    throw err;
  }
}

// ─── GitHub Helpers ────────────────────────────────────────────

async function createGithubRepo(token: string, name: string) {
  // First check if repo already exists
  const userRes = await fetch('https://api.github.com/user', {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
  });
  if (!userRes.ok) {
    throw new Error('GitHub token is invalid or expired. Please reconnect in Settings.');
  }
  const user = await userRes.json();

  const existingRes = await fetch(`https://api.github.com/repos/${user.login}/${name}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
  });
  if (existingRes.ok) {
    logger.info({ name }, 'Repo already exists, reusing');
    return existingRes.json() as Promise<{ html_url: string; full_name: string }>;
  }

  // Repo doesn't exist — create it
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name,
      private: false,
      auto_init: true,
      description: `Generated by Gen X Business Builder`,
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    const details = body.errors?.map((e: any) => e.message).join(', ') || '';
    throw new Error(`GitHub repo creation failed (${res.status}): ${body.message || res.statusText}${details ? ` — ${details}` : ''}`);
  }

  return res.json() as Promise<{ html_url: string; full_name: string }>;
}

async function pushFilesToRepo(
  token: string,
  owner: string,
  repo: string,
  files: Record<string, string>,
) {
  // Push each file via GitHub Contents API
  for (const [path, content] of Object.entries(files)) {
    // Check if file already exists (need SHA to update)
    let sha: string | undefined;
    const getRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
      },
    });
    if (getRes.ok) {
      const existing = await getRes.json();
      sha = existing.sha;
    }

    const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: `Add ${path}`,
        content: Buffer.from(content).toString('base64'),
        ...(sha ? { sha } : {}),
      }),
    });

    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      logger.warn({ path, error: body.message }, 'Failed to push file');
    }
  }
}

// ─── Vercel Helpers ────────────────────────────────────────────

async function createVercelProject(
  token: string,
  name: string,
  gitOwner: string,
  gitRepo: string,
  framework?: string,
  teamId?: string,
) {
  const qs = teamId ? `?teamId=${teamId}` : '';
  const res = await fetch(`https://api.vercel.com/v10/projects${qs}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name,
      framework: framework || 'nextjs',
      gitRepository: {
        type: 'github',
        repo: `${gitOwner}/${gitRepo}`,
      },
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(`Vercel project creation failed: ${body.error?.message || res.statusText}`);
  }

  return res.json() as Promise<{ id: string; name: string }>;
}

async function triggerVercelDeployment(token: string, projectId: string, teamId?: string) {
  const qs = teamId ? `?teamId=${teamId}` : '';
  const res = await fetch(`https://api.vercel.com/v13/deployments${qs}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: projectId,
      target: 'production',
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(`Vercel deployment failed: ${body.error?.message || res.statusText}`);
  }

  return res.json() as Promise<{ id: string; url: string }>;
}

function sanitizeRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 100);
}
